IOT stack docker compose
hedi-sfaxi/SIR-Terrarium pull request #4
Opened 2024-05-17 10:35 UTC by hedi-sfaxi

2024-05-17 15:27 UTC, dkgmgo commented on raspberry/services/influxdb/build_settings.yml
> +application: IOTstack
maybe change the name of the application

2024-05-17 15:29 UTC, dkgmgo commented on raspberry/volumes/grafana/data/alerting/1/__default__.tmpl
maybe we should delete this later

2024-05-17 15:35 UTC, augusto-moraes requested changes, later dismissed
just a few questions

2024-05-17 15:35 UTC, augusto-moraes commented on raspberry/services/docker-compose.save.yml
is it the same as docker-compose.yml ?
I don't think this one is really necessary

2024-05-17 15:35 UTC, augusto-moraes commented on raspberry/services/nodered/addons_list.yml
> +application: IOTstack
Consider changing the mame of the application here too ?

2024-05-17 15:35 UTC, dkgmgo commented on raspberry/volumes/portainer-ce/data/certs/cert.pem
I don't this we are suppose to git potainer's data cause it just for visualizing containers and it's not a real part of the project, so we should add 'raspberry/volumes/portainer-ce/' in the .gitignore

2024-05-24 12:17 UTC, hedi-sfaxi commented on raspberry/services/influxdb/build_settings.yml
> +application: IOTstack
Done

2024-05-24 12:40 UTC, dkgmgo approved these changes

2024-05-24 12:42 UTC, merged